version: '3.8'

services:
  counter:
    build:
      context: ./counter
      dockerfile: Dockerfile
    volumes:
      - ./db_data:/app/data
    networks:
      - hzz_network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./db_data:/app/data
    networks:
      - hzz_network
    depends_on:
      - counter

  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    volumes:
      - ./db_data:/app/data
    networks:
      - hzz_network
    depends_on:
      - counter
      - worker

volumes:
  db_data:
    driver: local

networks:
  hzz_network:
    driver: bridge
    driver_opts:
      type: none
      device: /data
      o: bind

